### ISSUE TITLE
unable to autofill confirmation form (Hubic::Error)

### ISSUE THREAD

**Issue by EnziinSystem** [sdalu/ruby-hubic#2]
/usr/local/rvm/gems/ruby-2.4.1/gems/hubic-0.0.3/lib/hubic.rb:190:in `get_request_code': unable to autofill confirmation form (Hubic::Error)
        from /usr/local/rvm/gems/ruby-2.4.1/gems/hubic-0.0.3/lib/hubic.rb:109:in `for_user'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/hubic-0.0.3/lib/hubic.rb:63:in `for_user'
        from drive.rb:9:in `<main>'

I use Ruby 2.4.1

**Comment by sdalu** [comment]
I don't have a Hubic account anymore. Unless someone provide a fix/pull-request or take ownership, this unfortunately won't be fix
